version: "3.6"

services:
  backend:
    container_name: doodoo-todo-api2
    build: .
    command: npm run dev
    working_dir: /usr/src/app/doodoo-todo-api2
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app/doodoo-todo-api2
      - /usr/src/app/node_modules/
